name: samurai

services:
  primary-db:
    container_name: primary-db
    image: postgres:17.2-alpine3.20
    environment:
      - POSTGRES_DB=${PRIMARY_DB_NAME}
      - POSTGRES_USER=${PRIMARY_DB_USER}
      - POSTGRES_PASSWORD=${PRIMARY_DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${DATA_DIR}/postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432
    restart: unless-stopped

  qdrant-db:
    container_name: qdrant-db
    image: qdrant/qdrant:v1.12.4-unprivileged
    networks:
      - app-network
    volumes:
      - ${DATA_DIR}/qdrant_data:/qdrant/storage
    ports:
      - 6333:6333
      - 6334:6334
    restart: unless-stopped

  backend:
    container_name: backend
    build: samurai-be
    environment:
      SPRING_PROFILES_ACTIVE: local
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
      PRIMARY_DB_HOST: ${PRIMARY_DB_HOST}
      PRIMARY_DB_PORT: ${PRIMARY_DB_PORT}
      PRIMARY_DB_NAME: ${PRIMARY_DB_NAME}
      PRIMARY_DB_PASSWORD: ${PRIMARY_DB_PASSWORD}
      PRIMARY_DB_USER: ${PRIMARY_DB_USER}
    networks:
      - app-network
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - primary-db
      - qdrant-db

  frontend:
    container_name: frontend
    build:
      context: samurai-fe
      args:
        - VITE_BASE_URL=${BACKEND_URL}
    networks:
      - app-network
    ports:
      - 80:8080
    restart: unless-stopped
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
