server:
  port: 8080

spring:
  application:
    name: ninja-be
  mvc:
    log-request-details: true
  autoconfigure:
    exclude: >
      org.springframework.ai.autoconfigure.anthropic.AnthropicAutoConfiguration
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ninja-db
    username: sa
    password: sa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
  # Important note: Only one ChatModel have to be available in application context
  # You can disable unused chat models using its 'enable' flag or by excluding model autoconfiguration
  ai:
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-large
          dimensions: 3072
      chat:
        enabled: true
        api-key: ${OPENAI_CHAT_API_KEY}
      image:
        enabled: false
      audio:
        speech:
          enabled: false
        transcription:
          enabled: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        ai: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

custom:
  allowed-origins: http://localhost:5173,http://localhost:4173,localhost
  # Note that both models have to be from single provider
  chat:
    model: gpt-4o
  task:
    model: gpt-4o-mini
