server:
  port: 8080

spring:
  application:
    name: ninja-be
  mvc:
    log-request-details: true
  autoconfigure:
    exclude: >
      org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration,
      org.springframework.ai.autoconfigure.vectorstore.qdrant.QdrantVectorStoreAutoConfiguration
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ninja-db
    username: sa
    password: sa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

custom:
  allowed-origins: http://localhost:5173,http://localhost:4173,localhost
  default-api-key: ${OPENAI_API_KEY}
  qdrant:
    client:
      host: "localhost"
      port: 6334
      tls: false
