server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    log-request-details: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:samurai-db
    username: sa
    password: sa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
  # Important note: Only one ChatModel have to be available in application context
  # You can disable unused chat models using its 'enable' flag or by excluding model autoconfiguration
  ai:
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        initialize-schema: true
        collection-name: documents
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        enabled: true
        options:
          model: text-embedding-3-large
          dimensions: 3072
      chat:
        enabled: true
      image:
        enabled: false
      audio:
        speech:
          enabled: false
        transcription:
          enabled: false
    anthropic:
      chat:
        enabled: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        ai: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

custom:
  loader:
    enabled: true
    bulk: false
  allowed-origins: http://localhost:5173,localhost
  jwt:
    passphrase: ${JWT_PASSPHRASE}
    expiration: 8h
    cookie:
      name: Authorization
      secure: false
      httpOnly: true
      prefix: Bearer_
      acceptAsHeader: true
      headerPrefix: "Bearer "
  # Note that both models have to be from single provider
  chat:
    model: gpt-4o
  task:
    model: gpt-4o-mini
  search:
    topK: 5
    similarityThreshold: 0.5
