package pl.ochnios.samurai.model.dtos.document;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.web.multipart.MultipartFile;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "${docs.dto.documentUpload}")
public class DocumentUploadDto {

    @Schema(description = "${docs.dto.documentUpload.file}")
    @NotNull(message = "must not be null")
    private MultipartFile file;

    @Schema(description = "${docs.dto.documentUpload.autogenerateDescription}")
    private Boolean autogenerateDescription;

    @Schema(description = "${docs.dto.document.title}")
    @NotBlank(message = "must not be blank or null")
    @Size(min = 3, message = "must have at least 3 characters")
    @Size(max = 255, message = "must have at most 255 characters")
    private String title;

    @Schema(description = "${docs.dto.document.description}")
    @Size(min = 3, message = "must have at least 3 characters")
    @Size(max = 2048, message = "must have at most 2048 characters")
    private String description;
}
